services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOSTNAME}

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A config worker --loglevel=info  # Update to your project name
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  celery-beat:  # New service for Celery Beat
    build: .
    command: celery -A config beat --loglevel=info  # Update to your project name
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  test:
    build: .
    command: pytest
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.base
      - PYTHONPATH=/app
    depends_on:
      - db

volumes:
  postgres_data:
